package com.towerswatson.rto.dpo.services._2010._01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-30T13:21:13.775+01:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01", name = "DpoService")
@XmlSeeAlso({ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.towerswatson.rto.smf.types._2010._01.ObjectFactory.class, com.towerswatson.rto.dpo.types._2010._01.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DpoService {

    @WebMethod(operationName = "GetPof", action = "http://towerswatson.com/rto/dpo/services/2010/01/DpoServiceContract/GetPof")
    @Action(input = "http://towerswatson.com/rto/dpo/services/2010/01/DpoServiceContract/GetPof", output = "http://towerswatson.com/rto/dpo/services/2010/01/DpoService/GetPofResponse", fault = {@FaultAction(className = DpoServiceGetPofConfigurationFaultContractFaultFaultMessage.class, value = "http://towerswatson.com/rto/dpo/services/2010/01/DpoService/GetPofConfigurationFaultContractFault"), @FaultAction(className = DpoServiceGetPofSevereFaultContractFaultFaultMessage.class, value = "http://towerswatson.com/rto/dpo/services/2010/01/DpoService/GetPofSevereFaultContractFault")})
    @WebResult(name = "PofResponse", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01", partName = "parameters")
    public PofResponse getPof(
        @WebParam(partName = "parameters", name = "PofRequest", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01")
        PofRequest parameters
    ) throws DpoServiceGetPofConfigurationFaultContractFaultFaultMessage, DpoServiceGetPofSevereFaultContractFaultFaultMessage;

    @WebMethod(operationName = "GetPofWithId", action = "http://towerswatson.com/rto/dpo/services/2010/01/DpoServiceContract/GetPofWithId")
    @Action(input = "http://towerswatson.com/rto/dpo/services/2010/01/DpoServiceContract/GetPofWithId", output = "http://towerswatson.com/rto/dpo/services/2010/01/DpoService/GetPofWithIdResponse", fault = {@FaultAction(className = DpoServiceGetPofWithIdConfigurationFaultContractFaultFaultMessage.class, value = "http://towerswatson.com/rto/dpo/services/2010/01/DpoService/GetPofWithIdConfigurationFaultContractFault"), @FaultAction(className = DpoServiceGetPofWithIdSevereFaultContractFaultFaultMessage.class, value = "http://towerswatson.com/rto/dpo/services/2010/01/DpoService/GetPofWithIdSevereFaultContractFault")})
    @WebResult(name = "PofResponse2", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01", partName = "parameters")
    public PofResponse2 getPofWithId(
        @WebParam(partName = "parameters", name = "PofRequestUsingMasterSet", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01")
        PofRequestUsingMasterSet parameters
    ) throws DpoServiceGetPofWithIdConfigurationFaultContractFaultFaultMessage, DpoServiceGetPofWithIdSevereFaultContractFaultFaultMessage;

    @WebMethod(operationName = "GetPofWithKey", action = "http://towerswatson.com/rto/dpo/services/2010/01/DpoServiceContract/GetPofWithKey")
    @Action(input = "http://towerswatson.com/rto/dpo/services/2010/01/DpoServiceContract/GetPofWithKey", output = "http://towerswatson.com/rto/dpo/services/2010/01/DpoService/GetPofWithKeyResponse", fault = {@FaultAction(className = DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage.class, value = "http://towerswatson.com/rto/dpo/services/2010/01/DpoService/GetPofWithKeyConfigurationFaultContractFault"), @FaultAction(className = DpoServiceGetPofWithKeySevereFaultContractFaultFaultMessage.class, value = "http://towerswatson.com/rto/dpo/services/2010/01/DpoService/GetPofWithKeySevereFaultContractFault")})
    @WebResult(name = "PofResponse2", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01", partName = "parameters")
    public PofResponse2 getPofWithKey(
        @WebParam(partName = "parameters", name = "PofRequestUsingKey", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01")
        PofRequestUsingKey parameters
    ) throws DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage, DpoServiceGetPofWithKeySevereFaultContractFaultFaultMessage;
}
