
package com.towerswatson.rto.dpo.services._2010._01;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-30T11:57:45.788+01:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ConfigurationFaultContract", targetNamespace = "http://towerswatson.com/rto/dpo/types/2010/01")
public class DpoServiceGetPofConfigurationFaultContractFaultFaultMessage extends Exception {
    
    private com.towerswatson.rto.dpo.types._2010._01.ConfigurationFaultContract configurationFaultContract;

    public DpoServiceGetPofConfigurationFaultContractFaultFaultMessage() {
        super();
    }
    
    public DpoServiceGetPofConfigurationFaultContractFaultFaultMessage(String message) {
        super(message);
    }
    
    public DpoServiceGetPofConfigurationFaultContractFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public DpoServiceGetPofConfigurationFaultContractFaultFaultMessage(String message, com.towerswatson.rto.dpo.types._2010._01.ConfigurationFaultContract configurationFaultContract) {
        super(message);
        this.configurationFaultContract = configurationFaultContract;
    }

    public DpoServiceGetPofConfigurationFaultContractFaultFaultMessage(String message, com.towerswatson.rto.dpo.types._2010._01.ConfigurationFaultContract configurationFaultContract, Throwable cause) {
        super(message, cause);
        this.configurationFaultContract = configurationFaultContract;
    }

    public com.towerswatson.rto.dpo.types._2010._01.ConfigurationFaultContract getFaultInfo() {
        return this.configurationFaultContract;
    }
}
