
package com.towerswatson.rto.dpo.services._2010._01;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-30T13:21:13.765+01:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ConfigurationFaultContract", targetNamespace = "http://towerswatson.com/rto/dpo/types/2010/01")
public class DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage extends Exception {
    
    private com.towerswatson.rto.dpo.types._2010._01.ConfigurationFaultContract configurationFaultContract;

    public DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage() {
        super();
    }
    
    public DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage(String message) {
        super(message);
    }
    
    public DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage(String message, com.towerswatson.rto.dpo.types._2010._01.ConfigurationFaultContract configurationFaultContract) {
        super(message);
        this.configurationFaultContract = configurationFaultContract;
    }

    public DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage(String message, com.towerswatson.rto.dpo.types._2010._01.ConfigurationFaultContract configurationFaultContract, Throwable cause) {
        super(message, cause);
        this.configurationFaultContract = configurationFaultContract;
    }

    public com.towerswatson.rto.dpo.types._2010._01.ConfigurationFaultContract getFaultInfo() {
        return this.configurationFaultContract;
    }
}
