package com.towerswatson.rto.dpo.services._2010._01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-30T13:10:10.096+01:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "DpoService", 
                  wsdlLocation = "file:/home/dsasikumar/codebase/consumesoap/src/main/resources/myService.wsdl",
                  targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01") 
public class DpoService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://towerswatson.com/rto/dpo/services/2010/01", "DpoService");
    public final static QName DefaultDpoServiceEndpoint = new QName("http://towerswatson.com/rto/dpo/services/2010/01", "DefaultDpoServiceEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/dsasikumar/codebase/consumesoap/src/main/resources/myService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DpoService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/dsasikumar/codebase/consumesoap/src/main/resources/myService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DpoService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DpoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DpoService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DpoService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DpoService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DpoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DpoService
     */
    @WebEndpoint(name = "DefaultDpoServiceEndpoint")
    public DpoService getDefaultDpoServiceEndpoint() {
        return super.getPort(DefaultDpoServiceEndpoint, DpoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DpoService
     */
    @WebEndpoint(name = "DefaultDpoServiceEndpoint")
    public DpoService getDefaultDpoServiceEndpoint(WebServiceFeature... features) {
        return super.getPort(DefaultDpoServiceEndpoint, DpoService.class, features);
    }

}
